spring:
  profiles:
    active: dev

  jackson:
#时间格式化
    date-format: yyyy-MM-dd HH:mm:ss
#时区设置
    time-zone: Asia/Chongqing
#数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  #druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
  #配置监控统计拦截的filters,去掉后监控界面SQL将无法统计,wall用于防火墙
    filters: stat,wall,log4j
  # 初始化数量
    initialSize: 5
  #最大活跃数
    maxActive: 20
  #配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMills: 60000
  #配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  #打开PSCache,并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  #通过connectProperties属性来打开mergeSql功能;慢SQl记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#redis
  redis:
   host: localhost
   port: 6379

#ehcache
  cache:
   type: ehcache
   ehcache:
    config: classpath:config/ehcache.xml

 #发送mail
  mail:
   host: smtp.exmail.qq.com
   username: fengyw@roncoo.com,service@roncoo.com,education@roncoo.com
   password:
   properties:
    mail:
     debug: true
     smtp:
      auth: true

#mybatis
mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.tpp.example.bean



#文件上传
http:
  multipart:
#默认支持文件上传.
   enabled: true
#支持文件写入磁盘.
   file-size-threshold: 0
#最大支持文件大小
   max-file-size: 2Mb
#最大支持请求大小
   max-request-size: 10Mb









#自定义配置
roncoo:
  secret: ${random.value}
  number: ${random.int}
  name: www.roncoo.com
  desc: the domain is ${roncoo.name}
